### ISSUE TITLE
向您诚挚推荐我的课表爬虫

### ISSUE THREAD

**Issue by j1g5awi** [voidf/bot_irori#8]
和每课一样使用教务系统的神奇接口，只需学号和姓名即可爬取课表。而每课可以用学号查询姓名，所以我们只需学号就可以爬取课表了（如果直接遍历一遍每课甚至可以反向查字典实现通过姓名查课表）。

我还专门写了个供QQ机器人发送的输出图片的功能，个人感觉还行。

https://github.com/Jigsaw111/Tools-for-CSU/tree/master/src/class-spider-lite

*另外，你打算什么时候 rebase下这些 commit ，真的有人能够从你这堆 commitmsg 里找到有用的信息么。。。*

**Comment by voidf** [comment]
行但是我想先把选课脚本接上去先（

~~不会有别人真的看commitmsg吧不会吧不会吧~~

~~找有用的信息倒是去v4分支的DEV.md啊）~~

**Comment by j1g5awi** [comment]
顺便一提，如果需要TRPG的功能可以去 [Nodice](https://github.com/thereisnodice/nodice) 找找 calculator.py 和 decks.py ，基本上可以即插即用（奇怪的广告出现了

~~爬了爬了，这就爬去看DEV~~

**Comment by voidf** [comment]
其实TRPG主要是想自己设计（

~~心有余而力不足罢了~~
